### PR TITLE
Updated travis build scripts (from rspec-dev)

### PR DESCRIPTION
**Pull request by benoittgt**
See: https://github.com/rspec/rspec-dev/pull/201

### CODE REVIEW

**Comment by benoittgt** [comment]
I will look at errors on 2.4.3 and 2.5 but meanwhile, I don't think you want this change for Rubocop?

**Comment by myronmarston** [comment]
> I don't think you want this change for Rubocop?

I think @xaviershay was working on reconciling the rubocop setting changes.  For now, undo that change in this branch.

**Comment by benoittgt** [comment]
Does this change https://github.com/rspec/rspec-core/pull/2524/commits/d9be90fede2d49a7af0fb7dd2a99513cad26d7dc should be implemented in rspec-dev?

**Comment by myronmarston** [comment]
> Does this change d9be90f should be implemented in rspec-dev?

Sure!  thanks for doing that.

**Comment by myronmarston** [comment]
Thanks!

**Pull request merged**
