### PR TITLE
Exclude example id in JSON output. Fixes #2125.

### LINKED ISSUE #2125: Runtime logging for shared_examples
Hello, I hope I'm right here with my concern.
We use json runtime logging in our project to have an idea of which tests take how long. For certain recurring expectations we have shared examples for which a log output looks like this:

``` json
{
  "description" : "raises an error",
  "full_description" : "ClassUnderTest raises an error if we expect that",
  "status" : "passed",
  "file_path" : "./spec/models/shared_examples/generic_examples.rb",
  "line_number" : 11,
  "run_time" : 0.135449016,
   "pending_message" : null
}
```

If we aggregate that (actually we use a feature of our CI platform for this) then we have the result that the file `./spec/models/shared_examples/generic_examples.rb` run for 4.2 minutes in total which is not actually useful information.
So my question, it is is possible, or feature request other wise would be: Is it possible to log the file path of the including file or let's better say the top level spec file which uses the shared examples (as it could be the case that shared examples make use of other shared examples)?
Or is there somehow useful conclusion to be drawn from aggregated runtime information about shared examples which I did not see yet?

### PR DESCRIPTION
**Pull request by xaviershay**
#2125

### CODE REVIEW

**Comment by JonRowe** [comment]
LGTM

**Comment by xmik** [comment]
Seems like the word was "export" instead of "exclude". :)

**Comment by JonRowe** [comment]
"Include" :)

**Comment by xaviershay** [comment]
sorry words are hard :(

**Pull request merged**
