### PR TITLE
Frozen string literals [experimental]

### PR DESCRIPTION
**Pull request by soulcutter**
Attempting to resolve whether or not Ruby 3+ frozen string literals represent a performance regression in 2.3. Related to #2264

My manual testing with `time rspec` shows the original code took around 10s and the frozen literal code took around 9.75 seconds (it was fairly consistent over multiple runs). Hardly scientific, but good enough for me.

Requires [rspec/rspec-support](../../rspec-support) to also use the `frozen-string-literals` branch to run.

### CODE REVIEW

**Comment by myronmarston** [comment]
LGTM!

**Comment by soulcutter** [comment]
I'd like to double-check to see if I missed any obscure references. Also, I imagine it's worth adding the magic comments to the spec files themselves (not sure if there are any issues in any of those... yet)

**Comment by myronmarston** [comment]
It would be nice to have a way to enforce that every ruby file under `lib` in RSpec has the magic comment.  I think newer versions of rubucop check that for you.  Worth upgrading and enforcing?

**Comment by soulcutter** [comment]
Good idea! I'm done for tonight, so the punch list right now looks like:

* [ ] Look for any string `concat` / `<<` I may have missed across the project
* [ ] Add magic comments to [rspec-expectations](../../rspec-expectations)
* [ ] Add magic comments to [rspec-mocks](../../rspec-mocks)
* [ ] Add magic comments to [rspec](../../rspec)
* [ ] Add magic comments to specs also
* [ ] Re-benchmark with all the libs converted
* [ ] Rubocop rules

**Comment by JonRowe** [comment]
I think we should do this from RSpec 4 onwards, it represents a potential breaking change in behaviour if any of these literals leak out.

**Comment by soulcutter** [comment]
I agree, this is breaking change material. Hard to audit every place we might leak a string literal. Major ruby version support is a good justification for a major version bump too (but not the only reason)

**Comment by myronmarston** [comment]
> I think we should do this from RSpec 4 onwards, it represents a potential breaking change in behaviour if any of these literals leak out.

It would be nice to not wait for RSpec 4 for this.  I think we can do it without any breaking changes.

* For strings that aren't exposed to users, make the changes necessary to work when it is frozen.
* For strings that are exposed to users, change from a string literal to `String.new(literal)` which provides an unfrozen string (in spite of the magic comment).

That should not break any users.

Actually, after writing that up, I've thought of a far better way to do this which is _guaranteed_ to not be a breaking change for any users: don't use the magic comment at all, opting instead for running our 2.3 build with the `--enable-frozen-string-literal` flag.

* The goal here is compatibility with frozen string mode, so we're both ready for ruby 3 when it ships and so that users running on 2.3 can opt to use `--enable-frozen-string-literal` while running their spec suite to opt-in to this if they want, without RSpec getting in their way.
* The goal is _not_ to force frozen strings on users (as the magic comment would do, for any strings originating as literals in that file).
* The flag removes the need for us to decorate every file with the magic comment, which is nice.
* The flag is a way for us to enforce that we are compatible with frozen strings mode but has absolutely no affect on end users.  Any changes to our code to satisfy that mode shouldn't affect users, either.

So I really think adding the flag to our ruby options for the 2.3 build is the way to go.

@soulcutter mentioned that this might have issues:

> `--enable-frozen-string-literal` would apply to gem dependencies we don't own, which may or may not have issues.

This is true, but the gem dependencies loaded in our spec suite are pretty minimal--mostly just our own gems, `diff-lcs` plus some light usage of a few other gems.  @soulcutter is right that those gems might prevent us from employing this strategy but I think it's worth a try.  If we run into problems from those gems, we can report them and hold off on doing more with this until its fixed.  Or maybe I'm not seeing something and the gems really will cause lots of problems for us -- but there's still no harm in trying.

**Comment by JonRowe** [comment]
> So I really think adding the flag to our ruby options for the 2.3 build is the way to go
👍 👍

**Comment by soulcutter** [comment]
Sure, worth a try! It was less work than I expected the first time around, so trying a different way should be even easier since I've seen the issues I expect to crop up. I'll take a shot tonight

Bradley Schaefer

**Comment by soulcutter** [comment]
Well, I didn't get too far. Simplecov and Coderay both have issues. Amusingly Simplecov's `version.rb` modifies a frozen object via `version = '0.11.2'; def version.major; … end`. I'll start creating working through these.

**Comment by mathieujobin** [comment]
from 10s to 9.5s is not a huge performance gain... is your test creating a lot of string?
could you check how many allocations were done with and without the option as described in this article
https://wyeworks.com/blog/2015/12/1/immutable-strings-in-ruby-2-dot-3

**Comment by soulcutter** [comment]
@mathieujobin Not really expecting huge perf gains by doing this, just compatibility. The important thing to me was that it wasn't a performance regression.

I lost steam on this because other libraries are broken. TBH I think the magic comment approach is better for the time being. I'm probably going to close all of these. It's starting to sound like Ruby 3 won't be forcing immutable strings anyway.

**Comment by soulcutter** [comment]
My current plan: close existing PRs, start fresh, add magic comments (commit), fix everything that breaks via `String.new`ing places which modify strings (commit), remove magic comments (commit).

This will not ensure that it will continue to function as we go forward with changes, but will at least give a decent base to work off of. Eventually I would like to work through the 3rd party libs too (because if immutable strings ever become default, rspec's going to break if its dependencies break), but it was too daunting for me to try to hit everything at once, so I'm not going to focus on that.

**Comment by myronmarston** [comment]
> My current plan: close existing PRs, start fresh, add magic comments (commit), fix everything that breaks via String.newing places which modify strings (commit), remove magic comments (commit).

> This will not ensure that it will continue to function as we go forward with changes, but will at least give a decent base to work off of. 

Your idea is a good one, but I think we can improve it even more.  Instead of committing magic comments and later removing them, what if we added a step to our CI build that added the magic comments to every `.rb` file in `lib` before running the spec suite?  That wouldn't require commits to add and remove magic comments, and would ensure things work with frozen string literals going forward since it would be a permanent part of our build.

**Comment by soulcutter** [comment]
Is the desire chiefly to not touch every file? I guess that could work

**Comment by myronmarston** [comment]
> Is the desire chiefly to not touch every file?

No, my main desire is to avoid putting a bunch of effort into this only to have it regress in the future because our CI builds aren't setup to enforce it.  If we add the magic comments and than revert them, we could easily regress on this manner in the future.  If we're going to put the effort in, I want to be able to announce to users, "RSpec 3.x works with frozen string literals" and have that statement remain true for all future releases.

Having the CI build add the magic comment to all the ruby files seems like it should allow the build to enforce this, w/o needing to worry about gems our spec suite relies upon not supporting frozen literals (as the `--enable-frozen-string-literal` flag suffers from) and w/o needing to worry about potentially breaking end users (as committing and keeping the magic comments would suffer from).

**Comment by soulcutter** [comment]
That makes sense. Although without the 3rd party libs eventually getting fixed I'd hesitate to say that RSpec works with frozen string literals (still) even if our code is alright.

**Comment by JonRowe** [comment]
@soulcutter we only have one 3rd party lib we actually depend on though, the rest are just used in our test suite.

**Comment by xaviershay** [comment]
Closing as stale (linked issue is still open)

**Pull request closed without merging**
