### PR TITLE
Avoid trying to apply `:suite` hooks to already defined example groups.

### PR DESCRIPTION
**Pull request by myronmarston**
This is a fix to #2189.

### CODE REVIEW

**Comment by JonRowe** [comment]
This makes sense to me, sorry for not spotting it as a potential issue when reviewing #2189, how did you catch it?

**Comment by myronmarston** [comment]
> This makes sense to me, sorry for not spotting it as a potential issue when reviewing #2189, how did you catch it?

Noticed it in the output while reworking #2175.

**Comment by JonRowe** [comment]
Do we need a regression check for this?

**Comment by myronmarston** [comment]
> Do we need a regression check for this?

The spec I added functions that way.  Our warnings preventer in rspec-support caused the spec I added to fail until I applied the fixes to config you see in this PR.  I didn't think it made sense to assert on the lack of warnings though, given we automatically fail every spec if it generates warnings.

**Comment by JonRowe** [comment]
Ah yeah, sorry :)

**Pull request merged**
