### PR TITLE
Avoid confusing `include` in example code for `include_context`

### PR DESCRIPTION
**Pull request by avit**
A small quality of life change: I think this makes it easier to read.

### CODE REVIEW

**Comment by JonRowe** [comment]
I'm not sure if thats any clearer, but I don't overly object, @benoittgt / @pirj, your thoughts?

**Comment by pirj** [comment]
The examples don't look too confusing to me as they are.

**Comment by benoittgt** [comment]
Hello @avit 

Thank for your proposal. I do not see a clear improvement in the documentation with your patch. 🤷

**Comment by avit** [comment]
Hi @benoittgt this was strictly for better readability, as seeing `include :shared_context` and `include_context` side-by-side was a bit mind-bending.

I wonder if the better change would be to use a different symbol for the example metadata, then.

**Pull request closed without merging**
