### PR TITLE
Updates from rspec-dev (2019-07-24)

### PR DESCRIPTION
**Pull request by benoittgt**
These are some updates, generated from rspec-dev's rake tasks.

### CODE REVIEW

**Comment by benoittgt** [comment]
Build not found. https://ci.appveyor.com/project/rspec/rspec-core/builds/26211151/job/avo32x5p1xcra46l

I don't understand yet why it is failing...

It is working for other people https://github.com/rubygems/rubygems/blob/master/appveyor.yml#L15-L16

**Comment by benoittgt** [comment]
@MSP-Greg Do you have an idea?

**Comment by benoittgt** [comment]
It is maybe related to PATH
https://github.com/rspec/rspec-core/blob/bf0c3a7df9036bbf57494d5d1890db8e2d462913/appveyor.yml#L21

VS

https://github.com/rubygems/rubygems/blob/master/appveyor.yml#L19

**Comment by MSP-Greg** [comment]
@benoittgt

I'm trying to type an explanation right now...

**Comment by MSP-Greg** [comment]
I'll give the medium length explanation, (hopefully) for the benefit of those unaware of the issues.

The default for Bundler & RubyGems is to install platform specific gems.  Typically, these are most common with exetensioin gems on Windows.  `ffi` is available as a pre-compiled gem for windows, but the constraint 'ffi (~> 1.9.25)' only allows a gem build before Ruby 2.6.0 release to be installed.  Since extension gems load the Ruby lib, and the Ruby library is version stamped with the ABI version...

So, you need change the constraint to a version of ffi that includes Ruby 2.6.

**Comment by benoittgt** [comment]
Ooook. Thank your very much @MSP-Greg

**Comment by MSP-Greg** [comment]
Sorry, I've worked with this stuff for so long...

One thing to check is https://rubygems.org/gems/ffi/versions/1.9.25-x64-mingw32, which shows the 'Required Ruby Version:' as "< 2.6, >= 2.0"

**Comment by MSP-Greg** [comment]
@benoittgt 

The line
https://github.com/rspec/rspec-core/blob/77dbc84657c5dc45e07a7fe0f5b02b4caeb6c9ad/Gemfile#L40

needs to change to
```ruby
gem 'ffi', '~> 1.11.0'
```

**Comment by benoittgt** [comment]
@JonRowe could you give me more rights on appveyor so I can trigger build manually?

Thanks

**Comment by JonRowe** [comment]
@benoittgt honestly appveyor has never liked me :joy: @myronmarston would you be able to help?

**Comment by myronmarston** [comment]
@JonRowe @benoittgt I just updated your user role from "User" to "Administrator" (along with @samphippen and @yujinakayama). So you should have access now.

**Comment by benoittgt** [comment]
Thanks a lot @myronmarston

**Comment by benoittgt** [comment]
@myronmarston this is strange I don't see the proper rights. 🤔 

Screenshot 2019-07-26 at 18 31 03

I cannot rerun a job. 

Screenshot 2019-07-26 at 18 30 53

**Comment by myronmarston** [comment]
@benoittgt are you logged in?  If you're logged in and don't see the "rerun" button than I have no idea.  Can you reach out to appveyor customer support and ask what we should do?  I don't really have the time to get more involved, unfortunately.

**Comment by MSP-Greg** [comment]
@benoittgt @myronmarston

Sorry I didn't look at this more thoroughly...

If you not logged in, you'll juts see 'Curent Build' and 'History'.  When logged in, additional items "Deployments', 'Events', and 'Serttings' should appear.


image

**Comment by JonRowe** [comment]
I still can't do anything either. maybe raise it with their support if you have time @benoittgt ?

**Comment by benoittgt** [comment]
I just contact them.

**Comment by benoittgt** [comment]
From the support:
>  From: Owen McDonnell (Support staff)
>
> Can you try logging in via email instead and let us know what you find. If you have not used email/password login before, go to https://ci.appveyor.com/forgot-password to set that up.
I suspect this is related to the [Important note](https://www.appveyor.com/docs/team-setup/#github-integration) in this part of the docs.

I logout using Github OAuth. Use my email password but I was not able to have admin access. I leave the RSpec role I had as collaborator. @myronmarston did you add "benoit@h*psandf*rk.com" can you try again?

**Comment by JonRowe** [comment]
FWIW it doesn't work with my email either

**Comment by myronmarston** [comment]
> I logout using Github OAuth. Use my email password but I was not able to have admin access. I leave the RSpec role I had as collaborator. @myronmarston did you add "benoit@h_psandf_rk.com" can you try again?

I just invited you.

**Comment by benoittgt** [comment]
Thanks @myronmarston 

It works!

**Comment by JonRowe** [comment]
@benoittgt can you add me?

**Comment by benoittgt** [comment]
@JonRowe I just did it. I remove your user and add it as admin. You should have receive and email.

**Comment by JonRowe** [comment]
Hurrah it works! However it seems there are issues with Ruby 2.6 and drb on Appveyor?

**Comment by benoittgt** [comment]
Yes. I need to start a VM on my computer and isolate the behavior. I don't get what is happening at the moment.

**Comment by ammelanie** [comment]
Hi there,

I've done some tests on Windows with ruby 2.6.3 and I've reproduced a similar issue with DRb, tests were breaking too.
After some search, I notice that the DRb server uri starts with my IP v6 address, I deactivate it on my computer, and tests gone green. If ip v6 is enable on Appveyor machine, it could be a clue. 


I'm trying to understand where is exactly the issue. For example, changing: 
```patch
-          drb_uri = "druby://localhost:#{RSpec.configuration.drb_port}"
+          drb_uri = "druby://my_ip_v6:#{RSpec.configuration.drb_port}"  
```
here https://github.com/rspec/rspec-core/blob/77dbc84657c5dc45e07a7fe0f5b02b4caeb6c9ad/lib/rspec/core/formatters/bisect_drb_formatter.rb#L17 works too, as if there is an issue while mapping `localhost` with the ip.

Hope it can help :)

**Comment by JonRowe** [comment]
Interesting, lets try adding ipv6 localhost to the allow list, its probably needed anyway

**Comment by benoittgt** [comment]
Yeah! Thanks @ammelanie

**Pull request merged**
