### PR TITLE
Removed deprecated option from .gemspec

### PR DESCRIPTION
**Pull request by takiy33**
rubyforge_project option is deprecated.

### CODE REVIEW

**Comment by JonRowe** [comment]
Confirmed this is no longer mentioned in the [docs](http://guides.rubygems.org/specification-reference/)

**Comment by myronmarston** [comment]
This should probably be done on the other repos, too.  @takiy33 -- care to take a stab at this?

And thanks!

**Comment by takiy33** [comment]
@myronmarston I will try it.

**Comment by takiy33** [comment]
I mistake it.

**Pull request merged**
