### PR TITLE
Fixing the default behaviour of `expose_dsl_globally`

### PR DESCRIPTION
**Pull request by JonRowe**
I'm going to tackle #1931 but in doing so I came across a cucumber scenario I believe is broken (the scenario doesn't describe what it does, and changing the scenario to match the description results in a failure) ping @myronmarston

### CODE REVIEW

**Comment by JonRowe** [comment]
Well found where that was going wrong...

**Comment by myronmarston** [comment]
This will certainly solve the problem, but I wonder if we can do away with the need to call `RSpec.configuration` from autorun.  Can we move where the DSL is exposed by default from `RSpec.configuration` into another spot that is automatically executed when rspec-core is loaded?  It would be nice to change this:

``` ruby
  def self.configuration
    @configuration ||= begin
                         config = RSpec::Core::Configuration.new
                         config.expose_dsl_globally = true
                         config
                       end
  end
```

to this:

``` ruby
  def self.configuration
    @configuration ||= RSpec::Core::Configuration.new
  end
```

**Comment by JonRowe** [comment]
@myronmarston I reworked this, WDYT

**Comment by myronmarston** [comment]
Better.  It still feels kinda weird to have to mutate the configuration from it's instantiated state at load time, though.  Here's an alternate solution that's based on your technique that I think I like better:

* Add `expose_globally!` right after the [RSpec::Core::DSL.expose_globally! method def](https://github.com/rspec/rspec-core/blob/bd6f7fd2e8d9153a4dd44dbf068be205d5890df1/lib/rspec/core/dsl.rb#L56-L64)
* Add `expose_globally!` right after the [RSpec::Core::SharedExampleGroup::TopLevelDSL.expose_globally! method def](https://github.com/rspec/rspec-core/blob/bd6f7fd2e8d9153a4dd44dbf068be205d5890df1/lib/rspec/core/shared_example_group.rb#L117-L121)

It seems more cleaner and more natural to me to put the responsibility in those places since they manage the DSL.

That said, I don't care too much and am happy to see this fix so if you prefer how you have it now, merge away once it's green.

**Comment by JonRowe** [comment]
> * Add `expose_globally!` right after the [RSpec::Core::DSL.expose_globally! method def](https://github.com/rspec/rspec-core/blob/bd6f7fd2e8d9153a4dd44dbf068be205d5890df1/lib/rspec/core/dsl.rb#L56-L64)
* Add `expose_globally!` right after the [RSpec::Core::SharedExampleGroup::TopLevelDSL.expose_globally! method def](https://github.com/rspec/rspec-core/blob/bd6f7fd2e8d9153a4dd44dbf068be205d5890df1/lib/rspec/core/shared_example_group.rb#L117-L121)

> It seems more cleaner and more natural to me to put the responsibility in those places since they manage the DSL.

I see those as splitting the responsibility personally... After all it's only because our config is supposed to default to exposing these globally that we do this at all... I'm looking forward to removing this line in 4.0 :)

**Comment by myronmarston** [comment]
Fair enough, merge away.

**Pull request merged**
