### PR TITLE
Include failure in pending output

### LINKED ISSUE #1792: It'd be nice for pending examples to print the failure that keeps them pending
When you tag a failing example as `pending` it still runs (and is expected to fail) but you are no longer given the failure in RSpec's output.  This is unfortunate, because for a BDD outside-in style workflow, it's really useful to be able to mark an end-to-end acceptance/feature spec as `pending` while you drive out the details with unit specs.  During this process it's nice to be able to re-run the acceptance spec and see where it's currently at.  As things currently work, you'd have to un-pend it, run it, and then re-pend it, which is pretty sub-optimal.

So, it'd be nice if `pending` specs displayed their failures

### PR DESCRIPTION
**Pull request by myronmarston**
Fixes #1792.

### CODE REVIEW

**Comment by myronmarston** [comment]
BTW, here's what this looks like in action:

screen shot 2015-01-12 at 12 57 05 am

That output is for this spec file:

``` ruby
RSpec.describe "Foo" do
  it "is pending", :pending => "because" do
    expect(1).to eq(2)
  end

  it "fails" do
    expect(1).to eq(2)
  end

  it 'is skipped', :skip do

  end
end
```

How do people feel the improved pending output looks? /cc @rspec/rspec

**Comment by myronmarston** [comment]
BTW, for reference, here's how that same spec file looks against master:

screen shot 2015-01-12 at 12 59 19 am

**Comment by myronmarston** [comment]
Woops, forgot to run the cukes and unsurprisingly, they are failing.  I'll take a stab at fixing that tomorrow.

**Comment by cefigueiredo** [comment]
Is there a way to make that behaviour optional? Something like a command `rspec --no-pending` maybe.

I know that there are the `skip` flag to put on tests and prevent it to run, but sometimes you just wanna mark a test as `pending` to make others know that the test is pending of more details or specification. And if even when we mark a test as `pending` it runs, it can make the time to test all spec unnecessarily large.

**Comment by myronmarston** [comment]
> Is there a way to make that behaviour optional? Something like a command `rspec --no-pending` maybe.

Which behavior, specifically?  Running pending specs?  Or including the failure details in the output for pending specs?  And I'm not sure what you would intend `--no-pending` to do.

Regardless, I think there are existing options that would serve your needs without adding the complexities of a `--no-pending` option.  You can use `--tag "~pending"` to exclude pending specs (which might be what you are looking for?) or you can use a custom formatter (using `--formatter` or `-f`) that does not include the failure details in the output for pending specs.

> I know that there are the skip flag to put on tests and prevent it to run, but sometimes you just wanna mark a test as pending to make others know that the test is pending of more details or specification. And if even when we mark a test as pending it runs, it can make the time to test all spec unnecessarily large.

The entire point of using `pending` over `skip` is to have the spec run, so that it verifies that the spec doesn't yet pass.  If that's no the semantic you want, then I recommend you don't use `pending`.  Both `pending` and `skip` can take a "reason" argument, so you can do this for your case:

``` ruby
it "does something", :skip => "pending more details or specification" do
end
```

**Comment by cefigueiredo** [comment]
I'm sorry if my text was a bit confusing. The behavior I mentioned was run `pending` specs.

The `-tag "~pending"` was exactly what I expected when I mentioned `--no-pending`. I just didn't know it yet. :)

I don't think that it would be necessary to change `pending` for `skip`. I like what pending represents, and run it on the CI, don't bother me, but wait unnecessary test when running the spec locally does.

So, I will continue with my flow, and just run rspec excluding the tag `pending` when running locally.

Thank you!

**Comment by myronmarston** [comment]
Glad to hear that works for you.  Another option for your case (that may actually work better for your case) is to leverage `config.define_derived_metadata` and use a custom metadata tag for these specs.  Something like:

``` ruby
RSpec.configure do |config|
  config.define_derived_metadata(:not_ready) do |meta|
    key = ENV['CI'] ? :pending : :skip
    meta[key] = "pending more details or specification"
  end
end
```

Then you tag some specs with `:not_ready` and they will be pending on CI but skipped in other environments.

**Comment by JonRowe** [comment]
LGTM, one of the AppVeyor builds is stuck but the other passed so merging.

**Pull request merged**
