### PR TITLE
Add seed section into JSON formatter

### PR DESCRIPTION
**Pull request by takkanm**
I want to seed infomation in JSON output. Because, current RSpec default order option is rand.

### CODE REVIEW

**Comment by xaviershay** [comment]
huh, I could have sworn we already did this. LGTM, thanks for contribution!

Looks like some of the build failures are relevant due to line number shifting in the spec files(!?) There has to be a better way...

**Comment by takkanm** [comment]
Thanks for your review. I'll try fix specs.

**Comment by takkanm** [comment]
I fixed CI failure. How about this?

**Comment by JonRowe** [comment]
Great! Thanks.

**Comment by takkanm** [comment]
Thank you!!

**Pull request merged**
