### PR TITLE
Rebased bennacer860 rubocop upgrade

### PR DESCRIPTION
**Pull request by soulcutter**
This branch does the cleanup I suggested in #2051

### CODE REVIEW

**Comment by JonRowe** [comment]
This doesn't resolve the discussion in the previous PR, where the consensus was we'd revert the whitespace changes and disable the rule instead.

**Comment by soulcutter** [comment]
Thanks for clarifying, @JonRowe - it wasn't clear to me that was what was holding it up. I was looking to get some momentum back on this to finish it up. Sounds like removing 6e2ce40 is all it will take then?

**Comment by JonRowe** [comment]
And 37c6435c3db9376d1ef0ff902515aa48635079e2 needs unpicking to remove the spacing changes too

**Comment by soulcutter** [comment]
@JonRowe That commit was tricky to pick out. Let me know if what I came up with meets your expectation.

**Comment by JonRowe** [comment]
LGTM

**Pull request merged**
