### PR TITLE
Add a spec for interrupt trapping in Runner

### PR DESCRIPTION
**Pull request by myrridin**
The Runner.trap_interrupt method was missing a spec. My goal is to extend interrupt handling per tenderlove's feature request https://github.com/rspec/rspec-core/issues/2055, but I wanted to make sure there was a spec in place first.

### CODE REVIEW

**Comment by myrridin** [comment]
It looks like this failed some Ruby versions in the Travis CI build, namely all JRuby and 1.9.2 MRI. I'm going to investigate to see if I can determine the issue.

**Comment by JonRowe** [comment]
The `1.9.2` build is possibly just a flake, and it's entirely possible that JRuby doesn't support signal handling

**Comment by myrridin** [comment]
JRuby claims to, though I wouldn't be surprised if there were differences. I'm currently working to diagnose the JRuby issue. 

If it turns out that this is non suppported, what's your recommendation? Is the spec not viable, or is it possible to limit this to MRI? What about 1.9.2? I'm having trouble getting the script to even run in that version though it's obviously setup on my end causing the issue.

**Comment by myrridin** [comment]
I can confirm that I'm able to trap SIGINT in a basic Ruby script with jruby 1.7.19 (1.9.3p551), and changing the trap syntax to pass in a proc object doesn't seem to help at all. Unfortunately I'm probably beyond my capacity on this one, but will continue poking.

**Comment by myrridin** [comment]
I have this gist which runs successfully. Per Charles Nutter I'm filing this as a JRuby bug, but don't seem to be able to reproduce in just JRuby.

**Comment by samphippen** [comment]
@myrridin is this still something you'd like to continue with? Would love to see this merged

**Comment by myrridin** [comment]
I can definitely take a fresh look. I've got an issue open on the jruby repo, but this doesn't appear to be an actual jruby bug. I'll do what I can to get this across the finish line. Thanks for checking in :-)

**Comment by samphippen** [comment]
@myrridin cool, thanks. Are you likely to be able to push more code in the next week?

**Comment by myrridin** [comment]
If I'm going to get it, it will be in the next week. If my second attempt doesn't work out I'll have to pass along as beyond my capabilities (or temporal capacity) :-) I'll do my best to update here regardles of the outcome.

**Comment by myrridin** [comment]
I changed up my approach here. This is borrowed directly from Rubocop: https://github.com/bbatsov/rubocop/blob/33aa8bcc3f50e545f97043b7eb7fd7228c4476da/spec/rubocop/cli_spec.rb#L2176

The idea is that instead of sending a SIGINT directly to the process as it runs, you capture the interrupt handlers that were created and manually call them.

The other solution was to add a sleep into the previous test, which felt wrong to do. The problem with signal handling is that there's no way I could figure out to block until the signal was processed. If I artificially delayed before the end of the spec I had full green every time, but the whole approach seemed to be going about it in the wrong way.

A friend of mine pointed me to this file and it seemed like a much better way to go about it.

**Comment by myrridin** [comment]
That passes jruby but fails MRI now :-( 

Please hold. I will definitely complete this. On a mission now.

**Comment by myrridin** [comment]
I went back to the basic version and tried to rebase it, along with a merge from master. I'm not used to working on larger repos like this, so let me know if I did something I shouldn't have. Expect these to pass this time, though I'll keep an eye on them.

**Comment by myrridin** [comment]
Ok I remade this PR to clean up the git issues I introduced: https://github.com/rspec/rspec-core/pull/2132

**Comment by JonRowe** [comment]
Thanks :)

**Pull request closed without merging**
