### PR TITLE
Deal with undefined errors_outside_of_examples_count

### PR DESCRIPTION
**Pull request by irpagnossin**
This pull request has two motivations:
- Protect SummaryNotification inner state against user misuse
- Back compatibility.

### CODE REVIEW

**Comment by benoittgt** [comment]
Hello

Thanks for your proposal.

Do you can provide a test that express "Protect SummaryNotification inner state against user misuse"?

Cheers 👋

**Comment by JonRowe** [comment]
I'd like to see a spec for the cause of this, we're not generally in favour of adding protection against people meddling with the internals (defensive coding) unless they can happen for legitimate reasons.

**Comment by irpagnossin** [comment]
Please ignore this pull request: a more thorough analysis of the case which motivated it showed the problem was generated by a misuse of SummaryNotification by an outdated gem.

**Comment by JonRowe** [comment]
Thanks for letting us know

**Pull request closed without merging**
