### PR TITLE
Synchronise changes from main / 3-11-maintenance to 4-0-dev

### PR DESCRIPTION
**Pull request by pirj**
Similar to https://github.com/rspec/rspec-support/pull/549

This is the result of `git merge main` and removal of what was mistakenly re-added during the merge, and minor fixes what became incompatible.

⚠️ I did not merge in `3-11-maintenance`, but at a glance, they are on par with `main`.

✅ No 3.11.1 bugfix release required

This brings 4-0 closer to parity with main.

### CODE REVIEW

**Comment by pirj** [comment]
I was lazy to hand-pick, and I `git merge`'d `main` into this PR's branch and removed what was mistakenly re-added or fixed what became incompatible.
In `rspec-support`, you just have 9 commits. Did you use some other method, @JonRowe ?

**Comment by JonRowe** [comment]
I've closed this because I prefer we don't do merges into the core branches like this, its better in my opinion to cherry-pick merge commits across (this is impossible in some cases where rebase merges have happened which is something I've been meaning to mention to you, we should always be doing merge commits or squash merges) the 4.0 situation is something I'm hoping to address in the next few weeks but if you want to cherry pick the prs across I'm happy for you to attempt that.

**Comment by JonRowe** [comment]
Equally I guess we could rebase the 4-0 changes in top of main as a "new" branch 
=

**Comment by pirj** [comment]
Makes sense 👍

**Pull request closed without merging**
