### PR TITLE
Update @samphippen's blog url

### PR DESCRIPTION
**Pull request by JonRowe**
It seems the apex url isn't working anymore.

### CODE REVIEW

**Comment by myronmarston** [comment]
This change is fine, although the fact that the old URL is now broken is obviously a cause for concern.  Various links to the non www version exist around the web, including from our blog.

@samphippen, did you intend to change your blog so that all non-www links broke?  Is there a way you can fix it back?  Is the `www` version of the link going to be more stable?

Depending on Sam's answers, we may want to revert this.

**Comment by JonRowe** [comment]
Yeah I'm hoping this is temporary and once @samphippen has time to check it out we should revert it...

**Comment by samphippen** [comment]
I think I've fixed this now. Sorry about that, I've literally no idea what happened as I didn't touch anything.

**Comment by samphippen** [comment]
for example: http://teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/

**Comment by JonRowe** [comment]
Redirects to www. is it supposed to?

**Comment by samphippen** [comment]
Yes, for some reason I couldn't get the root domain to work properly, so I implemented this as a fix.

**Pull request merged**
