### PR TITLE
Improve `rspec --init`.

### PR DESCRIPTION
**Pull request by myronmarston**
- Add lots more suggested settings to spec_helper.rb
  to give a great initial experience.
- Add a cucumber scenario that demonstrates that the
  settings generated by `rspec --init` are all valid.
  It doesn't demonstrate that they do what they are
  intended to do, but it protects against misspelled
  settings and whatnot.
- Remove old cruft.
- Put the init contents in their own files. Much
  cleaner than using heredocs.

I'd like some :eyes: on this to see what others think about all the settings this adds.  Is this overkill?  I think it'll make for a better starting experience to have more in the generated `spec_helper.rb` file.  Are there any settings I've added that shouldn't be included?  Anything I'm missing?

It would also be good to find a way to allow rspec-rails' generator to leverage this and build on top of it for the additional rails-specific stuff it adds.  I'm not sure of the best way to do that, though.

/cc @alindeman @JonRowe @xaviershay @soulcutter @samphippen

### CODE REVIEW

**Comment by slowjack2k** [comment]
Hi,

I have a question to those 2 helpers.

Say I have a spec  a_spec.rb which requires 'rails_spec_helper'
and a spec b_spec.rb which only requires 'spec_helper' .

When I run

> rspec a_spec.rb b_spec.rb

will rspec clean every thing up or will b_spec.rb run with every thing loaded?

Further more when I configure additional settings, for instance

>  # within rails_spec_helper
> config.use_transactional_fixtures = true

>  # within spec_helper
> config.use_transactional_fixtures = false

will they mess up?

regards
dieter

**Comment by myronmarston** [comment]
> will rspec clean every thing up or will b_spec.rb run with every thing loaded?

I'm not sure what you mean by "will rspec clean every thing up" but ruby does not provide a way to "unrequire" a file and it would be confusing/surprising for RSpec to do that to a file you have required -- so for the command you provided, the specs will run with both helper files loaded (assuming you are requiring the helper files at file load time rather than within an individual spec).

> will they mess up?

Yes.  `config.use_transactional_fixtures` is global state.  If you set it to one value, then change it to a new value, it'll be set to the new value.  I wouldn't recommend setting it in different files.

Besides, `use_transaction_fixtures` is not an rspec-core config option -- it's one added by rspec-rails to support rails testing and as such, it doesn't really make sense to set it in `spec_helper.rb` as `spec_helper.rb` is intended for "base" RSpec options and is meant to be usable w/o rails or rspec-rails (but also with rails and rspec-rails).

**Comment by slowjack2k** [comment]
Thanks for the explanation. It answers my question. With 'clean every thing up' I meant reset Rspec config and unload every thing accordingly. Until now I thought rspec will fork new processes or call system or some thing else. So that every spec is run in a clean environment.

`config.use_transactional_fixtures` was only an example but I should have been more accurate 
and call the 2 helpers `unit_spec_helper.rb` and `acceptance_spec_helper.rb`.

So when I set

```ruby
# acceptance_spec_helper.rb
RSpec.configure do |config|
config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
  end
```

```ruby
# unit_spec_helper.rb
RSpec.configure do |config|
config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end
```

It will screw depending on the execution order of my specs.

So whats the best way to deal with such different rspec configurations?

**Comment by myronmarston** [comment]
I'm not totally sure how you want your configuration to behave, but my best guess at what you want is this:

``` ruby
# unit_spec_helper.rb
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end
end
```

``` ruby
# acceptance_spec_helper.rb
RSpec.configure do |config|
  original_strategy = nil

  config.before(:context, :file_path => /spec\/acceptance/) do
    original_strategy = DatabaseCleaner.strategy
    DatabaseCleaner.strategy = :truncation
  end

  config.after(:context, :file_path => /spec\/acceptance/) do
    DatabaseCleaner.strategy = original_strategy
  end
end
```

This sets the default global strategy to `:transaction` but then in `acceptance_spec_helper.rb` sets things up so that before specs in `spec/acceptance` get run, the strategy is temporarily changed to `:truncation` and then changed back afterwards.

Is that the behavior you're trying to achieve?

**Comment by slowjack2k** [comment]
@myronmarston I think your solution is the nearest as I come to my goal and I appreciate your help. To explain it a little furthor my folder layout:

* spec/
   *  support
   *  acceptance
        * support
        * 
        *
   *  integration
       * support
        * 
        *
   * unit
        * support
        * 
        *
   * spec_helper.rb
   * rails_helper.rb
   * acceptance_spec_helper.rb
   * integration_spec_helper.rb
   * unit_spec_helper.rb


Unit Specs are without external deps (as far as you can achieve it within rails), so they require only spec_helper.rb & global support & unit support folder.

Integration specs are with external deps, so they require only rails_helper.rb & global support & integration support folder. They need the DB-Cleaner settings.

Acceptance are end to end tests so they require only rails_helper.rb & global support & acceptance support folder. Because these tests use for instance capybara so I can't use transactional fixtures. But furthor more I need some more around filters for instance:

```ruby
 config.after(:each) do
    wait_for_ajax if respond_to? :wait_for_ajax
  end
```
But this is only a starting point. The configurations will differ more and more over time I think.

When I get you right I have to ensure that I use `config.before(:context, :file_path => /spec\/acceptance/)`
and must ensure that my support methods, modules, classes don't interfer each other.

**Pull request merged**
