### PR TITLE
Test build

### PR DESCRIPTION
**Pull request by JonRowe**

### CODE REVIEW

**Comment by pirj** [comment]
```
/home/pirj/source/rspec-expectations/lib/rspec/matchers/dsl.rb:75: warning: method redefined; discarding old exist
/home/pirj/source/rspec-expectations/lib/rspec/matchers.rb:596: warning: previous definition of exist was here
```

**Comment by pirj** [comment]
https://github.com/alexrothenberg/ammeter/pull/68/files#diff-bffb236072e25d0e628532ccc5d2e03c2f3f4b446c93ea97ac6d215582cc5333R5

**Comment by JonRowe** [comment]
Yes I've been working on a fix, basically just rewriting rspec-rails tests to not need that matcher.

**Comment by pirj** [comment]
Wrapping the file path string into something that 

```diff
- subject(:generator_spec) { file("spec/generator/posts_generator_spec.rb") }
+ subject(:generator_spec) { Pathname.new(file("spec/generator/posts_generator_spec.rb")) }
```
fixes those issues.

But I think this would be better https://github.com/alexrothenberg/ammeter/pull/70

**Comment by JonRowe** [comment]
That PR will break out specs again as expect a string in places, did you check what effect that has on the contain matcher which we use extensively?

**Comment by pirj** [comment]
That’s weird. It was late night but I recall making that change in a live ammeter directory and that make our rspec-rails spec run green. I didn’t check cucumber though.
I didn’t think about the compatibility of your change and my ammeter patch though.
Let me check in the evening.

**Pull request closed without merging**
