### PR TITLE
With multiple inclusion filters, AND them instead of ORing them.

### LINKED ISSUE #2407: Interaction with focus and --only-failures
Hi there. I just noticed something odd with the interaction between the focus tag and `--only-failures`.

My rspec config is set up like so:
```ruby
RSpec.configure do |config|
  config.filter_run_when_matching :focus
  config.example_status_persistence_file_path = 'tmp/spec_results.txt'
end
```

In a few of my specs, I'm using `fdescribe` to only run a subset of my entire suite.

It appears that when using `rspec --only-failures` in this scenario, all of the focused specs are running, not just the failed ones.

```
$ rspec --only-failures
Run options:
  include {:focus=>true, :last_run_status=>"failed"}

Randomized with seed 5034
...F.
```

When I change all of the `fdescribe`s to `describe` it works as expected.
```
$ rspec --only-failures
Run options:
  include {:last_run_status=>"failed"}

Randomized with seed 50880
F
```

### PR DESCRIPTION
**Pull request by myronmarston**
Fixes #2407.

### CODE REVIEW

**Comment by JonRowe** [comment]
We've discussed this before, we need a better way of indicating what to do with multiple filters, this is a breaking change to the current behavioiur.

**Comment by myronmarston** [comment]
> We've discussed this before, we need a better way of indicating what to do with multiple filters, this is a breaking change to the current behaviour.

In what way is it a breaking change to our API?

**Comment by JonRowe** [comment]
```
     context "with multiple inclusion filters" do
 -        it 'includes objects that match any of them' do
 +        it 'only includes objects that match all of them' do
```

**Comment by myronmarston** [comment]
Changing a doc string doesn't mean we've broken a public API. In this case, I believe we've corrected an incorrect behavior.

What's an example of how this could be a breaking change for a user?  I can't think of one.

**Comment by JonRowe** [comment]
It affects tagging too:

```
rspec --tag something --tag other
Run options: include {:something=>true, :other=>true}
```
Currently that does a OR, now it'd do an AND we discussed this before in #1622

**Comment by myronmarston** [comment]
> Currently that does a OR, now it'd do an AND we discussed this before in #1622

Thanks.  I knew there was an issue where AND vs OR had come up before but I had forgotten what it was.

Anyhow, I wasn't involved much in that discussion.  Thinking about this issue now, I'm not convinced that changing the multi-tag filtering to AND instead of OR is a breaking change or SemVer violation.

While the user who reported #1622 figured out that filtering is currently OR'd, I don't think it's documented anywhere.  SemVer is about not making breaking changes to what your public docs say.  For better or worse, this area was not specified in our docs (in fact, I don't think I ever consciously thought about it) but now that I'm thinking about it, the current behavior seems buggy to me.  The behavior reported in #2407 is a direct consequence of filters ANDing and seems clearly like a bug.  I can't think of _any_  case where ORing filters is what you'd expect or want (can you?).  So, in my view, this is correcting behavior that is counterintuitive and surprising.  While I'm committed to SemVer, I think it does the project harm if we use it to avoid making useful changes to the project.  We adopted SemVer to better serve the needs of our users, but avoiding making this change because of SemVer feels like its getting in the way of the needs of our users.

For me, whether or not this change should be OK comes down to a key question: will this break anyone's spec suite?  I can't think of a way this will.  Anyone on an RSpec 3.x release should be able to upgrade to 3.6 w/o worry, and I don't think this has any affect on that important property.

What do others think? /cc @rspec/rspec

**Comment by JonRowe** [comment]
> For me, whether or not this change should be OK comes down to a key question: will this break anyone's spec suite? 

It will break anyone who uses tagging to seperate types of specs, like is often done with rails apps, (running several types together first and then running feature / integration tests)

**Comment by myronmarston** [comment]
@JonRowe can you provide a concrete example of the kind of OR filtering your project builds rely on?

The way I see it, ANDing filters seems much more natural.  As demonstrated in #2407, it's how at least some users expect it to work.  I've never wanted to OR filters before so I have a hard time imagining a use case, which is why a concrete example would be helpful.  IMO, we should have ANDed multiple filters all along; after all, currently there's no way to AND them.  But if the filters were ANDed, you could fake ORing them by running separate commands: `rspec --tag filter_1 && rspec --tag filter_2`.  (Not ideal, perhaps, but if it's a less common use case as I expect, it doesn't seem so bad).

**Comment by JonRowe** [comment]
> @JonRowe can you provide a concrete example of the kind of OR filtering your project builds rely on?

`rspec --tags type:model --tags type:helper` etc, basically anytime you want to run multiple sets together.

> But if the filters were ANDed, you could fake ORing them by running separate commands: `rspec --tag filter_1 && rspec --tag filter_2`.  (Not ideal, perhaps, but if it's a less common use case as I expect, it doesn't seem so bad).

Except thats really punitive with Rails due to boot up time etc.

I don't think you're being very fair here, the burden of proof you're placing here to prevent a significant behaviour change is quite high, this is existing behaviour that has existed for some time and has been documented in our tests as supposed to behave this way.

Granted it isn't documented in our Relish docs but our specs are equally capable of determining behaviour, so like it or not it is a significant change to the existing behaviour and whilst its not to the letter of SEMVER changing it is very much a violation of the spirit of SEMVER. We've had only 1 direct complaint about it (which was more a "missing part" of the api than a complaint) and 1 complication that could be worked around by resolving the former.

If you want to push ahead with this change as lead maintainer that's fine but you do so over my objections.

**Comment by TikiTDO** [comment]
Why not gate OR and AND behavior behind a separate param? Something like `--match-all` for AND and `--match-any` for OR, which can be a silent default. 

This way there is no change with to any previously existing code, and people that want to opt into AND behavior can do so by specifying a parameter.

**Comment by TikiTDO** [comment]
Also, as an alternative, if Conditional Filters can be modified to take a block which passes in an example, all of this behavior could be specified by the user:

Example:

```ruby
describe "test" do
  it "both", one: true, two: true, if: lambda {|example| RSpec::Core::MetadataFilter(:all?, RSpec.config.filter_manager.inclusions.rules, example.metadata)} do
    # ...
  end
end
```

From my perspective this would be the most ideal scenario, since I could adjust the behavior of my tests separately from any upstream assumptions regarding the best logical operator my testing library chooses to use, including throwing in mixed conditional logic.

**Comment by myronmarston** [comment]
@TikiTDO I like the idea of a way to toggle ANDing filters vs ORing them. I'd like to come up with better names than `--match-any` and `--match-all`, though.  Also: is it something that you would want to change for an individual spec run?  I'm thinking that it seems like the kind of thing to set for a project and leave, based on the kinds of filters a project is using (and I expect most projects to use the AND mode as it is more intuitive, IMO, especially given the issues opened in #2407 and #2426).  If it's true that it's not going to be toggled from the CLI often, I'd prefer it was an `RSpec.configure` option -- then you can set it in `spec_helper` and leave it.  I'm imagining we'd probably plan to default it to AND mode in 4.0, so the generated `spec_helper` could be updated to set it in 3.x to help people start transitioning, and then we could change the default in 4.0.

As for your lambda idea: lambdas are already supported when specifying filters (e.g. in `config.filter_run_including` or `config.filter_run_excluding`), but lambdas aren't treated as special when setting individual metadata values.  I also think that having to set a lambda like that to get the ANDing behavior you want is a pretty clunky API.  Plus we are considering deprecating and removing `:if`/`:unless` filters from RSpec 4 because we have to treat them as "special" to support them, and there isn't much benefit over just using the `if`/`unless` keywords.  For example, this:

``` ruby
RSpec.describe SomeClass do
  it "does something" do
    # ...
  end

  it "does something specific to JRuby", if: RUBY_PLATFORM == 'java' do
    # ...
  end
end
```

...could just as easily be:

``` ruby
RSpec.describe SomeClass do
  it "does something" do
    # ...
  end

  it "does something specific to JRuby" do
    # ...
  end if RUBY_PLATFORM == 'java'
end
```

...which uses Ruby built-in features rather than requiring special RSpec filtering support.

**Comment by TikiTDO** [comment]
@myronmarston Yeah, in the use case I cited originally I would need it on a per project basis. Personally I'm having trouble coming up with a situation where I would ever need both in one project, and from what I've seen of the code it would be a non-trivial task to adapt it to a finer granularity. Hell, if I was really desperate then some creative use of AND behavior, tags, helpers, and configuration parameters it would be possible to get OR behavior just by re-using code in different blocks.

I agree that the option does seem to fit pretty well within the context of `RSpec.configure`. In fact I'm already doing something similar by abusing inclusion/exclusion rules + lambdas, and an option like this would cut my `spec_helper.rb` file down by a few dozen lines.

As for the lambda behavior I proposed, that was actually the original idea when I started work on a full stack test platform for a client. My original plan was to write a common plugin that the other devs on the project could use to manage various scenarios, but I abandoned that for my inclusion/exclusion + lambda hack pretty early on. 

On one hand it would be nice to have the flexibility to make decisions about the example object in some sort of callback, but on the other hand this would be hard to manage outside an organization with strict documentation guidelines and ownership delineations. Usually this type of flexibility invites all sorts of bad designs and maintenance nightmares, so it's probably for the best that it not happen.

**Comment by abotalov** [comment]
I think in many cases people may would like to specify more complex conditions when telling RSpec which tests to run.
For example, if a test suite for web application is large and slow (tests use real browsers), it may be common to run only subset of the suite related to a particular set of functionality. E.g. `basket || checkout`.
Then they may like to additionally filter this set, e.g. by running only smoke tests like `(basket || checkout) && smoke`, or excluding some tests, e.g. `(basket || checkout) && !wip`.

Some other test frameworks have such feature:
* Cucumber (https://docs.cucumber.io/tag-expressions/)
* Nose (http://nose.readthedocs.io/en/latest/plugins/attrib.html)

**Comment by robotdana** [comment]
regardless of how we decide to cli specify "or" vs "and" please can we make it so under-the-hood uses of inclusion, such as `--only-failures` and `--next-failure` use "and". As it doesn't make sense in terms of how these flags are described for it to be "or" (https://github.com/rspec/rspec-core/issues/2526)

**Comment by myronmarston** [comment]
@robotdana `--only-failures` and `--next-failure` both already use "and".  "and" vs "or" really doesn't come into play in #2526.  The issue is that when you use a line number, RSpec interprets this as the user picking specific examples to run (as opposed to most other filters, which represents a _category_ of examples).  When a user takes the time to identify a specific example, they clearly want it to run, so RSpec gives precedence to the line number filter over any other exclusion filter.

**Comment by robotdana** [comment]
Oh, my use case is getting the list of failures from CI, then working through fixing them individually. There's no series of flags that will do what I want currently then

**Comment by JonRowe** [comment]
Why not just download the persistence file from CI and use `--next-failure`

**Comment by serhatbolsu** [comment]
Any plan to make this reality soon? It is a big struggle to go around this, while  having multiple conditions to combine with filtering @myronmarston

**Comment by JonRowe** [comment]
@serhatbolsu This is currently stale I'm afraid, Myron is less focused on RSpec these days and theres work to do to make this compatible with our current behaviour.

**Comment by myronmarston** [comment]
(Just closing as part of cleaning up old open PRs of mine.)

**Pull request closed without merging**
